packages:
  - apps/*
  - packages/*

nodeLinker: hoisted
engineStrict: true
saveExact: true

onlyBuiltDependencies:
  - "@swc/core"
  - esbuild

catalog:
  react: 19.1.0
  react-dom: 19.1.0
  react-native: 0.81.5
  "@types/react": 19.1.17

overrides:
  react: 19.1.0
  react-dom: 19.1.0
  react-native: 0.81.5
