/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AwaitingInvitationRouteImport } from './routes/awaiting-invitation'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MonitorRouteImport } from './routes/monitor'
import { Route as ProfessionalRouteImport } from './routes/professional'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SelectInstitutionRouteImport } from './routes/select-institution'
import { Route as StudentRouteImport } from './routes/student'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'
import { Route as ProfessionalIndexRouteImport } from './routes/professional/index'
import { Route as ProfessionalProfileRouteImport } from './routes/professional/profile'
import { Route as AdminInstitutionsIndexRouteImport } from './routes/admin/institutions/index'
import { Route as AdminInstitutionsInstitutionIdRouteImport } from './routes/admin/institutions/$institutionId'
import { Route as AdminInstitutionsNewRouteImport } from './routes/admin/institutions/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AwaitingInvitationRoute = AwaitingInvitationRouteImport.update({
  id: '/awaiting-invitation',
  path: '/awaiting-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorRoute = MonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionalRoute = ProfessionalRouteImport.update({
  id: '/professional',
  path: '/professional',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectInstitutionRoute = SelectInstitutionRouteImport.update({
  id: '/select-institution',
  path: '/select-institution',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionalIndexRoute = ProfessionalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfessionalRoute,
} as any)
const ProfessionalProfileRoute = ProfessionalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProfessionalRoute,
} as any)
const AdminInstitutionsIndexRoute = AdminInstitutionsIndexRouteImport.update({
  id: '/institutions/',
  path: '/institutions/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInstitutionsInstitutionIdRoute =
  AdminInstitutionsInstitutionIdRouteImport.update({
    id: '/institutions/$institutionId',
    path: '/institutions/$institutionId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminInstitutionsNewRoute = AdminInstitutionsNewRouteImport.update({
  id: '/institutions/new',
  path: '/institutions/new',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/awaiting-invitation': typeof AwaitingInvitationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/monitor': typeof MonitorRoute
  '/professional': typeof ProfessionalRouteWithChildren
  '/register': typeof RegisterRoute
  '/select-institution': typeof SelectInstitutionRoute
  '/student': typeof StudentRoute
  '/invite/$token': typeof InviteTokenRoute
  '/professional/profile': typeof ProfessionalProfileRoute
  '/professional/': typeof ProfessionalIndexRoute
  '/admin/institutions/$institutionId': typeof AdminInstitutionsInstitutionIdRoute
  '/admin/institutions/new': typeof AdminInstitutionsNewRoute
  '/admin/institutions/': typeof AdminInstitutionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/awaiting-invitation': typeof AwaitingInvitationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/monitor': typeof MonitorRoute
  '/register': typeof RegisterRoute
  '/select-institution': typeof SelectInstitutionRoute
  '/student': typeof StudentRoute
  '/invite/$token': typeof InviteTokenRoute
  '/professional/profile': typeof ProfessionalProfileRoute
  '/professional': typeof ProfessionalIndexRoute
  '/admin/institutions/$institutionId': typeof AdminInstitutionsInstitutionIdRoute
  '/admin/institutions/new': typeof AdminInstitutionsNewRoute
  '/admin/institutions': typeof AdminInstitutionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/awaiting-invitation': typeof AwaitingInvitationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/monitor': typeof MonitorRoute
  '/professional': typeof ProfessionalRouteWithChildren
  '/register': typeof RegisterRoute
  '/select-institution': typeof SelectInstitutionRoute
  '/student': typeof StudentRoute
  '/invite/$token': typeof InviteTokenRoute
  '/professional/profile': typeof ProfessionalProfileRoute
  '/professional/': typeof ProfessionalIndexRoute
  '/admin/institutions/$institutionId': typeof AdminInstitutionsInstitutionIdRoute
  '/admin/institutions/new': typeof AdminInstitutionsNewRoute
  '/admin/institutions/': typeof AdminInstitutionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/awaiting-invitation'
    | '/forgot-password'
    | '/login'
    | '/monitor'
    | '/professional'
    | '/register'
    | '/select-institution'
    | '/student'
    | '/invite/$token'
    | '/professional/profile'
    | '/professional/'
    | '/admin/institutions/$institutionId'
    | '/admin/institutions/new'
    | '/admin/institutions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/awaiting-invitation'
    | '/forgot-password'
    | '/login'
    | '/monitor'
    | '/register'
    | '/select-institution'
    | '/student'
    | '/invite/$token'
    | '/professional/profile'
    | '/professional'
    | '/admin/institutions/$institutionId'
    | '/admin/institutions/new'
    | '/admin/institutions'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/awaiting-invitation'
    | '/forgot-password'
    | '/login'
    | '/monitor'
    | '/professional'
    | '/register'
    | '/select-institution'
    | '/student'
    | '/invite/$token'
    | '/professional/profile'
    | '/professional/'
    | '/admin/institutions/$institutionId'
    | '/admin/institutions/new'
    | '/admin/institutions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AwaitingInvitationRoute: typeof AwaitingInvitationRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MonitorRoute: typeof MonitorRoute
  ProfessionalRoute: typeof ProfessionalRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  SelectInstitutionRoute: typeof SelectInstitutionRoute
  StudentRoute: typeof StudentRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awaiting-invitation': {
      id: '/awaiting-invitation'
      path: '/awaiting-invitation'
      fullPath: '/awaiting-invitation'
      preLoaderRoute: typeof AwaitingInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitor': {
      id: '/monitor'
      path: '/monitor'
      fullPath: '/monitor'
      preLoaderRoute: typeof MonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professional': {
      id: '/professional'
      path: '/professional'
      fullPath: '/professional'
      preLoaderRoute: typeof ProfessionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-institution': {
      id: '/select-institution'
      path: '/select-institution'
      fullPath: '/select-institution'
      preLoaderRoute: typeof SelectInstitutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professional/': {
      id: '/professional/'
      path: '/'
      fullPath: '/professional/'
      preLoaderRoute: typeof ProfessionalIndexRouteImport
      parentRoute: typeof ProfessionalRoute
    }
    '/professional/profile': {
      id: '/professional/profile'
      path: '/profile'
      fullPath: '/professional/profile'
      preLoaderRoute: typeof ProfessionalProfileRouteImport
      parentRoute: typeof ProfessionalRoute
    }
    '/admin/institutions/': {
      id: '/admin/institutions/'
      path: '/institutions'
      fullPath: '/admin/institutions/'
      preLoaderRoute: typeof AdminInstitutionsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/institutions/$institutionId': {
      id: '/admin/institutions/$institutionId'
      path: '/institutions/$institutionId'
      fullPath: '/admin/institutions/$institutionId'
      preLoaderRoute: typeof AdminInstitutionsInstitutionIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/institutions/new': {
      id: '/admin/institutions/new'
      path: '/institutions/new'
      fullPath: '/admin/institutions/new'
      preLoaderRoute: typeof AdminInstitutionsNewRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminInstitutionsInstitutionIdRoute: typeof AdminInstitutionsInstitutionIdRoute
  AdminInstitutionsNewRoute: typeof AdminInstitutionsNewRoute
  AdminInstitutionsIndexRoute: typeof AdminInstitutionsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminInstitutionsInstitutionIdRoute: AdminInstitutionsInstitutionIdRoute,
  AdminInstitutionsNewRoute: AdminInstitutionsNewRoute,
  AdminInstitutionsIndexRoute: AdminInstitutionsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ProfessionalRouteChildren {
  ProfessionalProfileRoute: typeof ProfessionalProfileRoute
  ProfessionalIndexRoute: typeof ProfessionalIndexRoute
}

const ProfessionalRouteChildren: ProfessionalRouteChildren = {
  ProfessionalProfileRoute: ProfessionalProfileRoute,
  ProfessionalIndexRoute: ProfessionalIndexRoute,
}

const ProfessionalRouteWithChildren = ProfessionalRoute._addFileChildren(
  ProfessionalRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AwaitingInvitationRoute: AwaitingInvitationRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MonitorRoute: MonitorRoute,
  ProfessionalRoute: ProfessionalRouteWithChildren,
  RegisterRoute: RegisterRoute,
  SelectInstitutionRoute: SelectInstitutionRoute,
  StudentRoute: StudentRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
