/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AwaitingInvitationRouteImport } from './routes/awaiting-invitation'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MonitorRouteImport } from './routes/monitor'
import { Route as ProfessionalRouteImport } from './routes/professional'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SelectInstitutionRouteImport } from './routes/select-institution'
import { Route as StudentRouteImport } from './routes/student'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'
import { Route as ProfessionalIndexRouteImport } from './routes/professional/index'
import { Route as ProfessionalManagementRouteImport } from './routes/professional/management'
import { Route as ProfessionalProfileRouteImport } from './routes/professional/profile'
import { Route as StudentIndexRouteImport } from './routes/student/index'
import { Route as StudentRoutineRouteImport } from './routes/student/routine'
import { Route as AdminInstitutionsIndexRouteImport } from './routes/admin/institutions/index'
import { Route as AdminInstitutionsInstitutionIdRouteImport } from './routes/admin/institutions/$institutionId'
import { Route as AdminInstitutionsNewRouteImport } from './routes/admin/institutions/new'
import { Route as ProfessionalManagementIndexRouteImport } from './routes/professional/management/index'
import { Route as ProfessionalManagementInvitationsRouteImport } from './routes/professional/management/invitations'
import { Route as ProfessionalManagementRolesRouteImport } from './routes/professional/management/roles'
import { Route as ProfessionalManagementTeamRouteImport } from './routes/professional/management/team'
import { Route as ProfessionalStudentsStudentIdRouteImport } from './routes/professional/students/$studentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AwaitingInvitationRoute = AwaitingInvitationRouteImport.update({
  id: '/awaiting-invitation',
  path: '/awaiting-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorRoute = MonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionalRoute = ProfessionalRouteImport.update({
  id: '/professional',
  path: '/professional',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectInstitutionRoute = SelectInstitutionRouteImport.update({
  id: '/select-institution',
  path: '/select-institution',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionalIndexRoute = ProfessionalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfessionalRoute,
} as any)
const ProfessionalManagementRoute = ProfessionalManagementRouteImport.update({
  id: '/management',
  path: '/management',
  getParentRoute: () => ProfessionalRoute,
} as any)
const ProfessionalProfileRoute = ProfessionalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProfessionalRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentRoutineRoute = StudentRoutineRouteImport.update({
  id: '/routine',
  path: '/routine',
  getParentRoute: () => StudentRoute,
} as any)
const AdminInstitutionsIndexRoute = AdminInstitutionsIndexRouteImport.update({
  id: '/institutions/',
  path: '/institutions/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInstitutionsInstitutionIdRoute =
  AdminInstitutionsInstitutionIdRouteImport.update({
    id: '/institutions/$institutionId',
    path: '/institutions/$institutionId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminInstitutionsNewRoute = AdminInstitutionsNewRouteImport.update({
  id: '/institutions/new',
  path: '/institutions/new',
  getParentRoute: () => AdminRoute,
} as any)
const ProfessionalManagementIndexRoute =
  ProfessionalManagementIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProfessionalManagementRoute,
  } as any)
const ProfessionalManagementInvitationsRoute =
  ProfessionalManagementInvitationsRouteImport.update({
    id: '/invitations',
    path: '/invitations',
    getParentRoute: () => ProfessionalManagementRoute,
  } as any)
const ProfessionalManagementRolesRoute =
  ProfessionalManagementRolesRouteImport.update({
    id: '/roles',
    path: '/roles',
    getParentRoute: () => ProfessionalManagementRoute,
  } as any)
const ProfessionalManagementTeamRoute =
  ProfessionalManagementTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => ProfessionalManagementRoute,
  } as any)
const ProfessionalStudentsStudentIdRoute =
  ProfessionalStudentsStudentIdRouteImport.update({
    id: '/students/$studentId',
    path: '/students/$studentId',
    getParentRoute: () => ProfessionalRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/awaiting-invitation': typeof AwaitingInvitationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/monitor': typeof MonitorRoute
  '/professional': typeof ProfessionalRouteWithChildren
  '/register': typeof RegisterRoute
  '/select-institution': typeof SelectInstitutionRoute
  '/student': typeof StudentRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/professional/management': typeof ProfessionalManagementRouteWithChildren
  '/professional/profile': typeof ProfessionalProfileRoute
  '/student/routine': typeof StudentRoutineRoute
  '/admin/': typeof AdminIndexRoute
  '/professional/': typeof ProfessionalIndexRoute
  '/student/': typeof StudentIndexRoute
  '/admin/institutions/$institutionId': typeof AdminInstitutionsInstitutionIdRoute
  '/admin/institutions/new': typeof AdminInstitutionsNewRoute
  '/professional/management/invitations': typeof ProfessionalManagementInvitationsRoute
  '/professional/management/roles': typeof ProfessionalManagementRolesRoute
  '/professional/management/team': typeof ProfessionalManagementTeamRoute
  '/professional/students/$studentId': typeof ProfessionalStudentsStudentIdRoute
  '/admin/institutions/': typeof AdminInstitutionsIndexRoute
  '/professional/management/': typeof ProfessionalManagementIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/awaiting-invitation': typeof AwaitingInvitationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/monitor': typeof MonitorRoute
  '/register': typeof RegisterRoute
  '/select-institution': typeof SelectInstitutionRoute
  '/invite/$token': typeof InviteTokenRoute
  '/professional/profile': typeof ProfessionalProfileRoute
  '/student/routine': typeof StudentRoutineRoute
  '/admin': typeof AdminIndexRoute
  '/professional': typeof ProfessionalIndexRoute
  '/student': typeof StudentIndexRoute
  '/admin/institutions/$institutionId': typeof AdminInstitutionsInstitutionIdRoute
  '/admin/institutions/new': typeof AdminInstitutionsNewRoute
  '/professional/management/invitations': typeof ProfessionalManagementInvitationsRoute
  '/professional/management/roles': typeof ProfessionalManagementRolesRoute
  '/professional/management/team': typeof ProfessionalManagementTeamRoute
  '/professional/students/$studentId': typeof ProfessionalStudentsStudentIdRoute
  '/admin/institutions': typeof AdminInstitutionsIndexRoute
  '/professional/management': typeof ProfessionalManagementIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/awaiting-invitation': typeof AwaitingInvitationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/monitor': typeof MonitorRoute
  '/professional': typeof ProfessionalRouteWithChildren
  '/register': typeof RegisterRoute
  '/select-institution': typeof SelectInstitutionRoute
  '/student': typeof StudentRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/professional/management': typeof ProfessionalManagementRouteWithChildren
  '/professional/profile': typeof ProfessionalProfileRoute
  '/student/routine': typeof StudentRoutineRoute
  '/admin/': typeof AdminIndexRoute
  '/professional/': typeof ProfessionalIndexRoute
  '/student/': typeof StudentIndexRoute
  '/admin/institutions/$institutionId': typeof AdminInstitutionsInstitutionIdRoute
  '/admin/institutions/new': typeof AdminInstitutionsNewRoute
  '/professional/management/invitations': typeof ProfessionalManagementInvitationsRoute
  '/professional/management/roles': typeof ProfessionalManagementRolesRoute
  '/professional/management/team': typeof ProfessionalManagementTeamRoute
  '/professional/students/$studentId': typeof ProfessionalStudentsStudentIdRoute
  '/admin/institutions/': typeof AdminInstitutionsIndexRoute
  '/professional/management/': typeof ProfessionalManagementIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/awaiting-invitation'
    | '/forgot-password'
    | '/login'
    | '/monitor'
    | '/professional'
    | '/register'
    | '/select-institution'
    | '/student'
    | '/invite/$token'
    | '/professional/management'
    | '/professional/profile'
    | '/student/routine'
    | '/admin/'
    | '/professional/'
    | '/student/'
    | '/admin/institutions/$institutionId'
    | '/admin/institutions/new'
    | '/professional/management/invitations'
    | '/professional/management/roles'
    | '/professional/management/team'
    | '/professional/students/$studentId'
    | '/admin/institutions/'
    | '/professional/management/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/awaiting-invitation'
    | '/forgot-password'
    | '/login'
    | '/monitor'
    | '/register'
    | '/select-institution'
    | '/invite/$token'
    | '/professional/profile'
    | '/student/routine'
    | '/admin'
    | '/professional'
    | '/student'
    | '/admin/institutions/$institutionId'
    | '/admin/institutions/new'
    | '/professional/management/invitations'
    | '/professional/management/roles'
    | '/professional/management/team'
    | '/professional/students/$studentId'
    | '/admin/institutions'
    | '/professional/management'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/awaiting-invitation'
    | '/forgot-password'
    | '/login'
    | '/monitor'
    | '/professional'
    | '/register'
    | '/select-institution'
    | '/student'
    | '/invite/$token'
    | '/professional/management'
    | '/professional/profile'
    | '/student/routine'
    | '/admin/'
    | '/professional/'
    | '/student/'
    | '/admin/institutions/$institutionId'
    | '/admin/institutions/new'
    | '/professional/management/invitations'
    | '/professional/management/roles'
    | '/professional/management/team'
    | '/professional/students/$studentId'
    | '/admin/institutions/'
    | '/professional/management/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AwaitingInvitationRoute: typeof AwaitingInvitationRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MonitorRoute: typeof MonitorRoute
  ProfessionalRoute: typeof ProfessionalRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  SelectInstitutionRoute: typeof SelectInstitutionRoute
  StudentRoute: typeof StudentRouteWithChildren
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awaiting-invitation': {
      id: '/awaiting-invitation'
      path: '/awaiting-invitation'
      fullPath: '/awaiting-invitation'
      preLoaderRoute: typeof AwaitingInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitor': {
      id: '/monitor'
      path: '/monitor'
      fullPath: '/monitor'
      preLoaderRoute: typeof MonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professional': {
      id: '/professional'
      path: '/professional'
      fullPath: '/professional'
      preLoaderRoute: typeof ProfessionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-institution': {
      id: '/select-institution'
      path: '/select-institution'
      fullPath: '/select-institution'
      preLoaderRoute: typeof SelectInstitutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professional/': {
      id: '/professional/'
      path: '/'
      fullPath: '/professional/'
      preLoaderRoute: typeof ProfessionalIndexRouteImport
      parentRoute: typeof ProfessionalRoute
    }
    '/professional/management': {
      id: '/professional/management'
      path: '/management'
      fullPath: '/professional/management'
      preLoaderRoute: typeof ProfessionalManagementRouteImport
      parentRoute: typeof ProfessionalRoute
    }
    '/professional/profile': {
      id: '/professional/profile'
      path: '/profile'
      fullPath: '/professional/profile'
      preLoaderRoute: typeof ProfessionalProfileRouteImport
      parentRoute: typeof ProfessionalRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/routine': {
      id: '/student/routine'
      path: '/routine'
      fullPath: '/student/routine'
      preLoaderRoute: typeof StudentRoutineRouteImport
      parentRoute: typeof StudentRoute
    }
    '/admin/institutions/': {
      id: '/admin/institutions/'
      path: '/institutions'
      fullPath: '/admin/institutions/'
      preLoaderRoute: typeof AdminInstitutionsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/institutions/$institutionId': {
      id: '/admin/institutions/$institutionId'
      path: '/institutions/$institutionId'
      fullPath: '/admin/institutions/$institutionId'
      preLoaderRoute: typeof AdminInstitutionsInstitutionIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/institutions/new': {
      id: '/admin/institutions/new'
      path: '/institutions/new'
      fullPath: '/admin/institutions/new'
      preLoaderRoute: typeof AdminInstitutionsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/professional/management/': {
      id: '/professional/management/'
      path: '/'
      fullPath: '/professional/management/'
      preLoaderRoute: typeof ProfessionalManagementIndexRouteImport
      parentRoute: typeof ProfessionalManagementRoute
    }
    '/professional/management/invitations': {
      id: '/professional/management/invitations'
      path: '/invitations'
      fullPath: '/professional/management/invitations'
      preLoaderRoute: typeof ProfessionalManagementInvitationsRouteImport
      parentRoute: typeof ProfessionalManagementRoute
    }
    '/professional/management/roles': {
      id: '/professional/management/roles'
      path: '/roles'
      fullPath: '/professional/management/roles'
      preLoaderRoute: typeof ProfessionalManagementRolesRouteImport
      parentRoute: typeof ProfessionalManagementRoute
    }
    '/professional/management/team': {
      id: '/professional/management/team'
      path: '/team'
      fullPath: '/professional/management/team'
      preLoaderRoute: typeof ProfessionalManagementTeamRouteImport
      parentRoute: typeof ProfessionalManagementRoute
    }
    '/professional/students/$studentId': {
      id: '/professional/students/$studentId'
      path: '/students/$studentId'
      fullPath: '/professional/students/$studentId'
      preLoaderRoute: typeof ProfessionalStudentsStudentIdRouteImport
      parentRoute: typeof ProfessionalRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminInstitutionsInstitutionIdRoute: typeof AdminInstitutionsInstitutionIdRoute
  AdminInstitutionsNewRoute: typeof AdminInstitutionsNewRoute
  AdminInstitutionsIndexRoute: typeof AdminInstitutionsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminInstitutionsInstitutionIdRoute: AdminInstitutionsInstitutionIdRoute,
  AdminInstitutionsNewRoute: AdminInstitutionsNewRoute,
  AdminInstitutionsIndexRoute: AdminInstitutionsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ProfessionalManagementRouteChildren {
  ProfessionalManagementInvitationsRoute: typeof ProfessionalManagementInvitationsRoute
  ProfessionalManagementRolesRoute: typeof ProfessionalManagementRolesRoute
  ProfessionalManagementTeamRoute: typeof ProfessionalManagementTeamRoute
  ProfessionalManagementIndexRoute: typeof ProfessionalManagementIndexRoute
}

const ProfessionalManagementRouteChildren: ProfessionalManagementRouteChildren =
  {
    ProfessionalManagementInvitationsRoute:
      ProfessionalManagementInvitationsRoute,
    ProfessionalManagementRolesRoute: ProfessionalManagementRolesRoute,
    ProfessionalManagementTeamRoute: ProfessionalManagementTeamRoute,
    ProfessionalManagementIndexRoute: ProfessionalManagementIndexRoute,
  }

const ProfessionalManagementRouteWithChildren =
  ProfessionalManagementRoute._addFileChildren(
    ProfessionalManagementRouteChildren,
  )

interface ProfessionalRouteChildren {
  ProfessionalManagementRoute: typeof ProfessionalManagementRouteWithChildren
  ProfessionalProfileRoute: typeof ProfessionalProfileRoute
  ProfessionalIndexRoute: typeof ProfessionalIndexRoute
  ProfessionalStudentsStudentIdRoute: typeof ProfessionalStudentsStudentIdRoute
}

const ProfessionalRouteChildren: ProfessionalRouteChildren = {
  ProfessionalManagementRoute: ProfessionalManagementRouteWithChildren,
  ProfessionalProfileRoute: ProfessionalProfileRoute,
  ProfessionalIndexRoute: ProfessionalIndexRoute,
  ProfessionalStudentsStudentIdRoute: ProfessionalStudentsStudentIdRoute,
}

const ProfessionalRouteWithChildren = ProfessionalRoute._addFileChildren(
  ProfessionalRouteChildren,
)

interface StudentRouteChildren {
  StudentRoutineRoute: typeof StudentRoutineRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentRoutineRoute: StudentRoutineRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AwaitingInvitationRoute: AwaitingInvitationRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MonitorRoute: MonitorRoute,
  ProfessionalRoute: ProfessionalRouteWithChildren,
  RegisterRoute: RegisterRoute,
  SelectInstitutionRoute: SelectInstitutionRoute,
  StudentRoute: StudentRouteWithChildren,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
